"""Ïntegrated the uuid

Revision ID: 372afe851311
Revises: 
Create Date: 2025-08-05 08:59:32.089294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372afe851311'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_table_id'), 'campaigns_table', ['id'], unique=False)
    op.create_table('talents_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('level', sa.Enum('LEVEL_100', 'LEVEL_200', 'LEVEL_300', 'LEVEL_400', 'LEVEL_500', 'GRADUATE', name='talentlevelenum'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('geozone', sa.Enum('NE', 'NW', 'NC', 'SE', 'SW', 'SS', name='geozoneenum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_talents_table_id'), 'talents_table', ['id'], unique=False)
    op.create_table('users_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_table_id'), 'users_table', ['id'], unique=False)
    op.create_table('talent_campaighn',
    sa.Column('talent_id', sa.UUID(), nullable=False),
    sa.Column('campaighn_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaighn_id'], ['campaigns_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talent_id'], ['talents_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('talent_id', 'campaighn_id')
    )
    op.create_table('performances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('talent_id', sa.UUID(), nullable=False),
    sa.Column('campaighn_id', sa.UUID(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['talent_id', 'campaighn_id'], ['talent_campaighn.talent_id', 'talent_campaighn.campaighn_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performances')
    op.drop_table('talent_campaighn')
    op.drop_index(op.f('ix_users_table_id'), table_name='users_table')
    op.drop_table('users_table')
    op.drop_index(op.f('ix_talents_table_id'), table_name='talents_table')
    op.drop_table('talents_table')
    op.drop_index(op.f('ix_campaigns_table_id'), table_name='campaigns_table')
    op.drop_table('campaigns_table')
    # ### end Alembic commands ###
