name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Production branch
    paths-ignore:
      - 'README.md'

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-auth
  DB_URL: ${{ secrets.DATABASE_URL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: prod-${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          build-args: |
            DATABASE_URL=${{ env.DB_URL }}
            SECRET_KEY=${{ env.SECRET_KEY }}

    #   - name: Clone ArgoCD repository
    #     uses: actions/checkout@v3
    #     with:
    #       repository: NineTalents-Agency/argocd
    #       token: $#{{ secrets.CHECKOUT_TOKEN }}
    #       path: auth

    #   - name: Update ArgoCD deployment.yaml
    #     run: |
    #       sed -i "s|image: .*$|image: $IMAGE_NAME:$IMAGE_TAG|g" auth/auth/deployment.yml

    #   - name: Commit and push changes to ArgoCD repo
    #     run: |
    #       cd auth
    #       git config --global user.email "chriscrsov@gmail.com"
    #       git config --global user.name "chriscrsov"
    #       git add auth/deployment.yml
    #       git commit -m "Update image tag to $IMAGE_TAG"
    #       git push
